#!/bin/bash
DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

#i3
rm -rf $HOME/.config/i3
ln -s $DOTFILES/kitty $HOME/.config/i3

#ranger
rm -rf $HOME/.config/ranger
ln -s $DOTFILES/kitty $HOME/.config/ranger

#kitty
rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

#tmux
rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

#nvim
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim
